# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"

  deploy_int:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'dev-deploy'}}
    steps:
      - name: Deploy to int
        run: echo "deploying to int"

  deploy_qat:
    needs: deploy_int
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to qat
        run: echo "deploying to qat"

  deploy_stg:
    needs: deploy_qat
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to stg
        run: echo "deploying to stg"

  deploy_prd:
    needs: deploy_stg
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prd
        run: echo "deploying to prd"
